name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "python -m pip install sphinx==5.0.2 sphinx-gallery myst-nb sphinx_book_theme  sphinxcontrib-fulltoc myst-parser sphinxcontrib.video sphinx-book-theme matplotlib readthedocs-sphinx-search geopandas sphinx-toolbox sphinx-panels"
        docs-folder: "docs/"
        build-command: "sphinx-build -ab html ./source ./build"
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: docs/build/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/